### ISSUE TITLE
[Bug] Game Does not end when we push bulls in to the lake trap

### ISSUE THREAD

**Issue by RedwanIbneSerajKhan** [jaimeenahn/goHomeBulls#122]
# Description of the Bug
According to your MVP feature, 
   " There will be a few traps like lake if bulls fall into the traps the game will be ended." When I pushed 2 bulls in the lake, the game did not end.

# Pictorial Description of Bug
As you can see from the picture that I pushed 1 bull to the barn and pushed 2 of them to the lake but the game did not stop. 
![gohomebullscriticalbug](https://user-images.githubusercontent.com/28854577/38773523-9109ce6e-401c-11e8-8497-e1f4022ae05c.png)

**Comment by zhaosec** [comment]
Thank you very much for your reporting. We will fix the bug ASAP.

**Comment by zhaosec** [comment]
The bug has been fixed, and we made a hotfix release. Thank you.
