### ISSUE TITLE
[Major Bug] Feature of buying food to increase stamina from 'stamina shop' not working when I am out of Stamina

### ISSUE THREAD

**Issue by RedwanIbneSerajKhan** [jaimeenahn/goHomeBulls#123]
# Description of Bug

I cannot increase my stamina by buying foods from the stamina shop when I am out of stamina even when I have dining dollars at my disposal.

# Video Description
I have made a video of the time I have experienced this bug. You can check it out after unzipping the file.
[GoHomeBullsMajorBug.zip](https://github.com/jaimeenahn/goHomeBulls/files/1911484/GoHomeBullsMajorBug.zip)

**Comment by zhaosec** [comment]
Thanks for your report. According to the MVP "If stamina becomes zero, the game will be finished automatically". So the game will be aborted after the stamina becomes zero. But you are able to increase your stamina when the stamina is not zero by buying food at the shop.

**Comment by RedwanIbneSerajKhan** [comment]
I think you should at least enable this as a feature if not a bug. I have 'Dining Dollars' and a 'Stamina shop', why should the game stop in this situation? It should continue until I run out of dollars and stamina also.

**Comment by zhaosec** [comment]
We will think about this feature late on this semester. But it is our intention to do that.
