### ISSUE TITLE
im not sure if these are the bugs?

### ISSUE THREAD

**Issue by nenanou** [jaimeenahn/goHomeBulls#124]
on the game page it says press "S" to start and press "E" to edit the map, however, on my MacBook, I actually have to press s and e.  s and e with caps lock isn't working and also on the wiki beta testing page, 

 Testing Procedure:

On the gaming page, music will be automatically played when we start the game (after pressing 'S'). There will be a box-shaped button with play and pause image on the top-right side of the page. Click that button.

the music start automatically when we enter the web page, not after we start the game.

Thank you!

**Comment by nenanou** [comment]
also, the ranking system is not working. no register button was found in the Hall of Frame page.

**Comment by zhaosec** [comment]
Thanks for your reporting, we are fixing it right now. For the ranking system, it is doesn't have a login system. You can write your name and score on it directly.
