### ISSUE TITLE
Lack of Stamina issue

### ISSUE THREAD

**Issue by Deepaklather** [jaimeenahn/goHomeBulls#127]
When we start playing this game, the stamina is 100%. But when we are out of stamina and then we use stamina shop to buy some stamina using dinning dollars. At that time, we are unable to add stamina to the stamina bar and the game stops working. 

![1](https://user-images.githubusercontent.com/36175612/38787386-82b5c7c0-40fb-11e8-95b7-6849d66398f9.PNG)

You can see I have already bought some stamina but it not adding to stamina bar. 

![2](https://user-images.githubusercontent.com/36175612/38787388-85ac6682-40fb-11e8-8b5b-f4e841ff2df2.PNG)

**Comment by zhaosec** [comment]
As we indicate in MVP "If stamina become zero, the game will be finished automatically Stamina drinks will show up randomly in each stages. Therefore, maintaining stamina is the key." Thank you for your report.
