### ISSUE TITLE
Make at least 2 maps

### ISSUE THREAD

**Issue by jaimeenahn** [jaimeenahn/goHomeBulls#44]
~~I moved stamina bar out from the game screen.  
Our goal is make decrease stamina when we push the bulls.
It is possible to put this bar into game it is way easy to count keyboard interrupt.
However, if I move it, it looks messy that why I'm trying to move it outside.
I tried couple of things but it is not easy to get keyboard interrupt outside of game and pass remain stamina to next stage.~~

~~As I asked a few days days ago, our app doesn't work on IE. We were tried to solve this problem. But it is too hardcoded. So, I asked you to solve this problem. When we execute program in IE, it looks like this : The game doesn't work with white screen. We cannot find difference between chrome and IE how hard we searched about it. Plz this is our really help wanted issue.~~

If you see the maps.js, there will be 3 maps until now. To make game more fun, I want you to make more stages at least 2, that has to be able to be cleared. The clear condition of each stage is in scene/scene_main.js . It is called isWin() and isLose() function. Mind that if the number of houses are bigger than the number of bulls, game will be over. Sorry about changing issue so many time.

**Comment by jzeng4ub** [comment]
What exactly do you mean by 'outside of game'? By keyboard interrupt do you mean when a directional key is pressed or number of times any bull is pushed?

**Comment by jaimeenahn** [comment]
Do you mind if I ask you a favor?
If you don't could you make it run on IE instead of this?

**Comment by jaimeenahn** [comment]
what is your ubit?
