### ISSUE TITLE
Game character animation 

### ISSUE THREAD

**Issue by zhaosec** [jaimeenahn/goHomeBulls#47]
In our game, the game character will change direction and move after user press the "↑ ← ↓ →" . Currently, our project doesn't have any animation or process of game character change his direction, my code just simply change character's image accordingly after user press the key. 
I would want you to add animation of the game character change his direction. For example, the game character is currently facing the upper side, now the user pressed ↓ key then the character would turn around and facing the downside. During this process, the game character needs a animation during the process of turning around, make it feel spontaneous.

**Comment by rmredder** [comment]
Hi, I was assigned to this task for collaboration. Could you tell me what file(s) the game character is located in and are there any tools I will need or that you recommend to work on the project?
