### ISSUE TITLE
[bug]Stamina didn't refresh

### ISSUE THREAD

**Issue by kai123456** [jaimeenahn/goHomeBulls#61]
In each level there is a 100% for stamina and reducing 1% per second. 
However, when you complete a level, the stamina did not refresh, it is reducing continuously.

When I close the lack of stamina box, the stamina remain as "Lack of STAMINA", and the player can still move.

**Comment by jaimeenahn** [comment]
What we are trying to accomplish is maintaining remain stamina but buy recover it by using shopping system which will be updated between each stages.

The player shouldn't move after LACK OF STAMINA, we will make it shut down after the message comes out.
